export const APP_NAME : string;
export const APP_BACKEND_PORT : string;
export const APP_FRONTEND_PORT  : string;
export const APP_USER_API  : string;
export const APP_PROFILE_API  : string;
export const APP_SIGNUP_URL : string;
export const APP_LOGIN_URL  : string;
export const APP_VERIFYACCOUNTCODE_URL : string;
export const API_ENDPOINT: string;
export const APP_RESET_PASSWORD : string;
export const APP_RESET_PASSWORD_NOW: string;
export const APP_AUTHENTICATE_TOKEN_NAME: string;
export const APP_PROFILE_GET_BY_USERID: string;
export const APP_TODO_API: string;
export const APP_TODO_POST: string;
export const APP_PROFILE_PUT: string;
export const APP_PROFILE_GET_BY_OWN: string;
export const APP_TODO_SEARCH: string;