name: Node.js CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: self-hosted
    environment: production
    steps:
      # Fix permissions before proceeding
      # - name: Fix permissions for GitHub Actions Runner
      #   run: |
      #     sudo chmod -R 777 /var/www/my-bullet-journal/_work/my-bullet-journal/my-bullet-journal
      #     sudo chown -R $(whoami) /var/www/my-bullet-journal/_work/my-bullet-journal/my-bullet-journal

      - name: Check out the repository
        uses: actions/checkout@v2

      # Client setup and build
      - name: Set up Node.js for Client
        uses: actions/setup-node@v4
        with:
          node-version: "20.9.0" # Specify the Node.js version needed for the client

      - name: Install client dependencies
        working-directory: /var/www/my-bullet-journal/_work/my-bullet-journal/my-bullet-journal/client
        run: |
          npm install --legacy-peer-deps

      - name: Build client
        working-directory: /var/www/my-bullet-journal/_work/my-bullet-journal/my-bullet-journal/client
        run: npm run build

      # Server setup
      - name: Set up Node.js for Server
        uses: actions/setup-node@v4
        with:
          node-version: "20.9.0" # Specify the Node.js version needed for the server

      - name: Install server dependencies
        working-directory: /var/www/my-bullet-journal/_work/my-bullet-journal/my-bullet-journal/server
        run: |
          npm install

      # Install PM2 in client
      - name: Install PM2
        working-directory: /var/www/my-bullet-journal/_work/my-bullet-journal/my-bullet-journal/client
        run: npm install -g pm2

      # Deployment steps
      - name: Deploy client
        working-directory: /var/www/my-bullet-journal/_work/my-bullet-journal/my-bullet-journal/client
        run: |
          pm2 start npm --name "my-bullet-journal" -- run preview
          pm2 save
          sudo service nginx restart

      # Install PM2 in server
      - name: Install PM2
        working-directory: /var/www/my-bullet-journal/_work/my-bullet-journal/my-bullet-journal/server
        run: npm install -g pm2

      # Deploy in server
      - name: Deploy server
        working-directory: /var/www/my-bullet-journal/_work/my-bullet-journal/my-bullet-journal/server
        run: |
          pm2 start index.js --name my-app
          pm2 save
          sudo service nginx restart
