name: Deploy

on:
  push:
    branches:
      - main # Replace with your target branch

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Node.js for Client
        uses: actions/setup-node@v4
        with:
          node-version: "20.9.0" # Specify the Node.js version needed for the client
          cache: "npm" # Enable cache for npm
          cache-dependency-path: /var/www/my-bullet-journal/_work/my-bullet-journal/my-bullet-journal/client/package-lock.json # Path to the client's lock file

      - name: Install dependencies for client
        working-directory: /var/www/my-bullet-journal/_work/my-bullet-journal/my-bullet-journal/client
        run: npm install

      - name: Build client
        working-directory: /var/www/my-bullet-journal/_work/my-bullet-journal/my-bullet-journal/client
        run: npm run build

      - name: Set up Node.js for Server
        uses: actions/setup-node@v4
        with:
          node-version: "20.9.0" # Specify the Node.js version needed for the server
          cache: "npm" # Enable cache for npm
          cache-dependency-path: /var/www/my-bullet-journal/_work/my-bullet-journal/my-bullet-journal/server/package-lock.json # Path to the server's lock file

      - name: Install dependencies for server
        working-directory: /var/www/my-bullet-journal/_work/my-bullet-journal/my-bullet-journal/server
        run: npm install

      - name: Deploy client
        run: |
          # Replace with your actual deployment commands
          rsync -avz /var/www/my-bullet-journal/_work/my-bulletjournal/my-bullet-journal/client/build/ your-user@your-server:/path/to/deployment

      - name: Deploy server
        run: |
          # Replace with your actual deployment commands
          rsync -avz /var/www/my-bullet-journal/_work/my-bulletjournal/my-bullet-journal/server/ your-user@your-server:/path/to/deployment
          ssh your-user@your-server 'pm2 restart all'
