name: Node.js CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      # Client setup and build
      - name: Set up Node.js for Client
        uses: actions/setup-node@v4
        with:
          node-version: "20.9.0" # Specify the Node.js version needed for the client

      - name: Install client dependencies
        working-directory: /var/www/my-bullet-journal/_work/my-bullet-journal/my-bullet-journal/client
        run: |
          npm install --legacy-peer-deps

      - name: Build client
        working-directory: /var/www/my-bullet-journal/_work/my-bullet-journal/my-bullet-journal/client
        run: npm run build

      # Server setup
      - name: Set up Node.js for Server
        uses: actions/setup-node@v4
        with:
          node-version: "20.9.0" # Specify the Node.js version needed for the server

      - name: Install server dependencies
        working-directory: /var/www/my-bullet-journal/_work/my-bullet-journal/my-bullet-journal/server
        run: |
          npm install

      # Deployment steps
      - name: Deploy client
        working-directory: /var/www/my-bullet-journal/_work/my-bullet-journal/my-bullet-journal/client
        run: |
          pm2 restart 1
          pm2 save
          sudo service nginx restart
