name: Deploy

on:
  push:
    branches:
      - main # Replace with your target branch

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      # Client setup and build
      - name: Set up Node.js for Client
        uses: actions/setup-node@v4
        with:
          node-version: "20.9.0" # Specify the Node.js version needed for the client

      - name: Check Client lock file
        working-directory: /var/www/my-bullet-journal/_work/my-bullet-journal/my-bullet-journal/client
        run: ls -la package-lock.json

      - name: Clean install client dependencies
        working-directory: /var/www/my-bullet-journal/_work/my-bullet-journal/my-bullet-journal/client
        run: |
          rm -rf node_modules package-lock.json
          npm install --legacy-peer-deps

      - name: Build client
        working-directory: /var/www/my-bullet-journal/_work/my-bullet-journal/my-bullet-journal/client
        run: npm run build

      # Server setup
      - name: Set up Node.js for Server
        uses: actions/setup-node@v4
        with:
          node-version: "20.9.0" # Specify the Node.js version needed for the server

      - name: Check Server lock file
        working-directory: /var/www/my-bullet-journal/_work/my-bullet-journal/my-bullet-journal/server
        run: ls -la package-lock.json

      - name: Clean install server dependencies
        working-directory: /var/www/my-bullet-journal/_work/my-bullet-journal/my-bullet-journal/server
        run: |
          rm -rf node_modules package-lock.json
          npm install --legacy-peer-deps

      # Deployment steps
      - name: Deploy client
        run: |
          # Replace with your actual deployment commands
          rsync -avz /var/www/my-bullet-journal/_work/my-bullet-journal/my-bullet-journal/client/build/ your-user@your-server:/path/to/deployment

      - name: Deploy server
        run: |
          # Replace with your actual deployment commands
          rsync -avz /var/www/my-bullet-journal/_work/my-bullet-journal/my-bullet-journal/server/ your-user@your-server:/path/to/deployment
          ssh your-user@your-server 'pm2 restart all'
